default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: homegroup_forum_development

test: &test
  <<: *default
  database: homegroup_forum_test

production:
  <<: *default

