# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e41048c55a8a6d9f0c4707701215a4c22da71d392639b02777223007fc8527821c35598bd0c1721bbb2e3807dcdf84e66b6579482f354f1fa8a1434f3604527a

test:
  secret_key_base: 8443c1a84dd4f69ee34af34f918dd23e7a564178601e341d8ea3774614843a73e4090e064b423d1121e38ff14cb6429532d1dc3c7ef8c6847d7865653f820efe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
